rooms = [rm_coloring_dart,
rm_coloring_grid_4x5,
rm_edge_coloring_petersen_star,
rm_total_coloring_dart,
rm_graceful_s5,
rm_decomp_triangle,
rm_decomp_bowtie,
rm_decomp_triforce,
rm_decomp_k7,
rm_coloring_p2,
rm_coloring_petersen_star,
rm_coloring_kite,
rm_coloring_petersen_claw,
rm_coloring_petersen_circle,
rm_coloring_dodecahedron,
rm_coloring_categorical_4];
current = 0;
